openapi: 3.0.1
info:
  title: monster-succubus
  x-cortex-tag: monster-succubus
  x-cortex-custom-metadata:
    alignment: neutral-good
    type: fey
    challenge_rating: 8
    legendary: false
    armor_class: 11
    hit_points: 126
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-succubus
      alias: github-token-test
